### ISSUE TITLE
Fig.2 in your paper is misleading

### ISSUE THREAD

**Issue by wzm2256** [D1noFuzi/cmd_styletransfer#2]
Apparently:
1. 1D OT is not equivalent to 1D MMD.
2. 1D MMD may fail, but 1D OT can surely align these two distributions without difficulty.

Although these flaws have no influence on your algorithm, it weakens your argument: why on earth do we need CMD?. 
Therefore if I were the reviewer I would not suggest publication without modification of this part of the paper.

Nevertheless you could suggest OT is hard to compute or whatever in this case.

Anyway, Fig.2 is misleading and may confuse a large number of readers.

**Comment by D1noFuzi** [comment]
Hi @wzm2256, 
I think you have misread big parts of section 3.2. We do not claim that **Maximum Mean Discrepancy (MMD)** based approaches are equivalent to **Gaussian reduced Optimal Transport (OT)** in our paper, but rather that **Moment Matching (MM!) with ONLY first and second order** is in the 1D case. Just observe, that MM with only first and second order moments reduces to matching mean and variance and that Gaussian OT is defined by the mean and covariance matrix, which reduces to the variance in 1D.
Regarding your second claim, you are absolutely right. OT can surely align the distributions. However, we are not looking at the general form of OT, but only its Gaussian approximation due to the efficient computation (clearly stated at the end of section 3.2) and as a toy example in Fig. 2. Of course in 1D OT would be efficiently computable (since it can be reduced to CDFs under certain assumptions).

I think if you carefully read the paper, Fig. 2 is not misleading, but rather helpful to readers.

**Comment by wzm2256** [comment]
OK, I got it.
